name: Gitopia Mirror

on: //[push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Gitopia Mirror Action
        uses: gitopia/gitopia-mirror-action@v0.1.2
        with:
          gitopiaWallet: "${{ secrets.GITOPIA_WALLET }}"
          branch: "master"
          remoteUrl: "gitopia://SerYX59R-T2e0kpEGn6yXNr8o_oDSpoZ72Nqt5pxIsY/Cryptovoxels-Models-Library"
